create table if not exists producto(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(200) not null,
    precio DECIMAL(10,2) not null,
    stock int not null
);

create table if not exists usuario(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(200) not null,
    correo VARCHAR(200) not null
);
